// generateProjectReportPDF.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateProjectReportPDF = (project, report) => {
  const doc = new jsPDF();

  // Title Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text('Project Report Summary', 105, 20, null, null, 'center');

  // Project Info Table
  autoTable(doc, {
    startY: 30,
    head: [['Field', 'Details']],
    body: [
      ['Project Name', project.name || 'N/A'],
      ['Status', report.status || 'N/A'],
      ['Utilization', report.utilization ? `${report.utilization}%` : 'N/A'],
      ['Hours Spent', report.hoursSpent || 'N/A'],
    ],
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 11,
      cellPadding: 5,
      textColor: 50,
    },
    headStyles: {
      fillColor: [240, 240, 240],
      textColor: 0,
      fontStyle: 'bold',
    },
  });

  // Dependencies Section
  const nextY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Dependencies', 14, nextY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const dependencies = report.dependencies || 'None';
  doc.setTextColor(70, 70, 70);
  doc.text(doc.splitTextToSize(dependencies, 180), 14, nextY + 8);

  // Footer
  const footerY = 285;
  doc.setDrawColor(200);
  doc.line(10, footerY, 200, footerY); // horizontal line
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150);
  doc.text('Confidential Report - Generated By Vairavan - Koinnovation Timesheet', 105, footerY + 5, null, null, 'center');

  // Save PDF
  const fileName = `${(project.name || 'project').replace(/\s+/g, '_')}_Report.pdf`;
  doc.save(fileName);
};
